theme = 'papercolor-light'

[editor]
rulers = [80]
auto-pairs = false
idle-timeout = 200
completion-timeout = 200

[editor.gutters]
layout = ["diff", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "separator", "version-control", "separator", "file-name", "file-type", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "separator", "position-percentage"]

[editor.soft-wrap]
# don't show anything when soft wrapping a line
wrap-indicator = ""
# soft wrap at the window's text width. for most cases, this is the full width
# of the window. languages can override this, see the languages.toml file
wrap-at-text-width = true

[editor.indent-guides]
render = true
character = "┊"
 
[editor.lsp]
# in-line hints about variable types, function parameters, etc
display-inlay-hints = true

# KEY BINDINGS, NORMAL MODE
[keys.normal]
# vim muscle memory ;-)
G = "goto_file_end"
# in case we forgot how to stop selecting things
esc = ["collapse_selection", "keep_primary_selection"]
x = ["extend_line", "select_mode"] # fantastic mapping, teaches you to use select_mode in the process, allowing precise selection, at the cost of one key to exit
# increment and decrement what's under the selection
minus = "decrement" # 'minus' not '-', for parsing reasons
"=" = "increment" # default is format_selections via LSP

[keys.normal.g]
# more logical now that the default "ge" is no longer useful thanks to the
# binding "G" above
e = "goto_line_end"

[keys.normal.'\']
# shortcut for my personal wiki
w = ":open ~/Documents/text-vault/index.md"

# double-tap '[' to go up a markdown heading
[keys.normal.'[']
'[' = '@?^#+\s+.*$<ret>'

# double-tap ']' to go down a markdown heading
[keys.normal.']']
']' = '@/^#+\s+.*$<ret>'

# KEY BINDINGS, SELECT MODE
[keys.select]
# vim muscle memory ;-)
G = "goto_file_end"

[keys.select.g]
# more logical now that the default "ge" is no longer useful thanks to the
# binding "G" above
e = "goto_line_end"

